# Generated by Django 4.0.3 on 2022-11-30 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('butyswiata', '0002_alter_shoes_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='category',
        ),
        migrations.AddField(
            model_name='shoes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='butyswiata.category'),
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='color',
        ),
        migrations.AddField(
            model_name='shoes',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='butyswiata.color'),
        ),
    ]
