# Generated by Django 4.0.3 on 2022-11-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butyswiata', '0003_remove_shoes_category_shoes_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='upload',
            new_name='images',
        ),
    ]
