# Generated by Django 4.0.3 on 2022-11-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butyswiata', '0004_rename_upload_shoes_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='images',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
