# Generated by Django 4.0.3 on 2022-11-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butyswiata', '0006_alter_shoes_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='images',
            new_name='image',
        ),
    ]
