# Generated by Django 4.0.3 on 2022-12-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butyswiata', '0010_alter_shoes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='size',
        ),
        migrations.AddField(
            model_name='shoes',
            name='size',
            field=models.ManyToManyField(to='butyswiata.size'),
        ),
    ]
