# Generated by Django 4.0.3 on 2022-11-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butyswiata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name': 'Shoe', 'verbose_name_plural': 'Shoes'},
        ),
    ]
